version: 2

multi-ecosystem-groups:
  python:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: "python"
    patterns: ["*"]
    versioning-strategy: increase

  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "python"
    patterns: ["*"]
