repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-added-large-files
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [ --fix ]
        description: Run linter with fixes enabled
      - id: ruff-format
        description: Run formatter
-   repo: local
    hooks:
      - id: tox_lint
        name: lint
        description: Run lint
        entry: pdm run tox -e lint
        language: system
        pass_filenames: false
      - id: tox_test
        name: test
        description: Run test
        entry: pdm run tox -e py
        language: system
        pass_filenames: false
