[tox]
env_list = py{310,311,312,313}-dbt{15,16,17,110,111},lint,docs

skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
description = Run tests
dependency_groups = test
setenv =
    dbt15: DBT_VERSION=1.5
    dbt16: DBT_VERSION=1.6
    dbt17: DBT_VERSION=1.7
    dbt110: DBT_VERSION=1.10
    dbt111: DBT_VERSION=1.11
commands =
    dbt{15,16,17,110,111}: uv pip install --upgrade 'dbt-core~={env:DBT_VERSION}.0'
    coverage run -m pytest

[testenv:lint]
runner = uv-venv-lock-runner
description = Run lint
dependency_groups = lint, test
commands =
    ruff check .
    mypy .

[testenv:docs]
runner = uv-venv-lock-runner
description = Build docs
dependency_groups = docs
commands =
    mkdocs build --clean
