[tox]
env_list = py{310,311,312,313}-dbt{15,16,17,110,111},lint,docs

skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
description = Run tests
dependency_groups = test
commands =
    dbt15: uv pip install --upgrade 'dbt-core>=1.5,<1.6'
    dbt16: uv pip install --upgrade 'dbt-core>=1.6,<1.7'
    dbt17: uv pip install --upgrade 'dbt-core>=1.7,<1.8'
    dbt110: uv pip install --upgrade 'dbt-core>=1.10,<1.11'
    dbt111: uv pip install --upgrade 'dbt-core>=1.11,<1.12'
    pytest
    coverage run -m pytest

[testenv:lint]
runner = uv-venv-lock-runner
description = Run lint
dependency_groups = lint, test
commands =
    ruff check .
    mypy .

[testenv:docs]
runner = uv-venv-lock-runner
description = Build docs
dependency_groups = docs
commands =
    mkdocs build --clean
