name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release
    runs-on: ubuntu-slim
    permissions:
      id-token: write
      contents: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-docs.outputs.page_url }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: 3.13
          enable-cache: false
      - name: Build
        run: uv build
      - name: Publish package distributions to PyPI
        run: |
          uv publish
      - name: Install dependencies
        run: |
          uv sync --group docs
      - name: Build docs
        run: |
          uv run dbt-score list -f markdown -n dbt_score.rules.generic --title Generic > docs/rules/generic.md
          uv run dbt-score list -f markdown -n dbt_score.rules.macros --title Macros > docs/rules/macros.md
          uv run zensical build --clean
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: site
      - name: Deploy docs to GitHub Pages
        id: deploy-docs
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
      - name: Create GitHub release
        run: gh release create "$TAG" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
